version: '3.7'

services:
  app:
    build:
        context: ..
        dockerfile: .devcontainer/Dockerfile
    volumes:
        - ..:/workspace:cached
    network_mode: service:db
    command: sleep infinity
  unleash:
    image: unleashorg/unleash-server
    ports:
      - 4242:4242
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://unleash:unleash@db:5432/unleash

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - unleash-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: unleash
      POSTGRES_DB: unleash
      POSTGRES_PASSWORD: unleash

volumes:
  unleash-postgres-data:
